name: CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: read
jobs:
  compile-with-bazel:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          scl enable devtoolset-7 bash 
          ./clean.sh
          ./build.sh
          bazel test  //...
